name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    environment: DjangoCI
    env: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_S3_REGION: ${{ vars.AWS_S3_REGION }}
      AWS_STORAGE_BUCKET_NAME: ${{ vars.AWS_STORAGE_BUCKET_NAME }}
      AWS_S3_CUSTOM_DOMAIN: ${{ vars.AWS_S3_CUSTOM_DOMAIN }}
      AWS_S3_MEDIA_LOCATION: ${{ vars.AWS_S3_MEDIA_LOCATION }}
      AWS_S3_STATIC_LOCATION: ${{ vars.AWS_S3_STATIC_LOCATION }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
